title: Page

tabs:
  content:
    preset: page
    fields:
      content:
        type: textarea
  meta:
    preset: page
    fields:
      meta:
        type: entity
        extends: fields/meta
      metaInherit:
        type: entity
        extends: fields/meta
